dotenv: .env
keys: ${KEYS}
networks:
    moonriver:
        collateralCToken: "0xd0670AEe3698F66e2D4dAf071EB9c690d978BFA8" # mUSDC
        borrowCToken: "0xa0D116513Bd0B8f3F14e6Ea41556c6Ec34688e0f" # mxcKSM
    moonriver-fork:
        collateralCToken: "0xd0670AEe3698F66e2D4dAf071EB9c690d978BFA8" # mUSDC
        borrowCToken: "0xa0D116513Bd0B8f3F14e6Ea41556c6Ec34688e0f" # mxcKSM
        cmd_settings:
            unlock:
                # Address of first minter in minters array of underlying token
                - 0x10c6b61DbF44a083Aec3780aCF769C77BE747E23
    bsc-test:
        collateralCToken: "0xD5C4C2e2facBEB59D0216D0595d63FcDc6F9A1a7" # vUSDC
        borrowCToken: "0x3619bdDc61189F33365CC572DF3a68FB3b316516" # vMATIC
