dotenv: .env
keys: ${KEYS}
networks:
    moonriver:
        cToken: "0xd0670AEe3698F66e2D4dAf071EB9c690d978BFA8" # mUSDC
    moonriver-fork:
        cToken: "0xd0670AEe3698F66e2D4dAf071EB9c690d978BFA8" # mUSDC
        cmd_settings:
            unlock:
                # Address of first minter in minters array of underlying token
                - 0x10c6b61DbF44a083Aec3780aCF769C77BE747E23
